server:
  port: 7600
  servlet:
    context-path: /api/v1

spring:
  application:
    name: barbershop-user-service
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_BARBERSHOP_USER_URL}
    username: ${MYSQL_BARBERSHOP_USER_USERNAME}
    password: ${MYSQL_BARBERSHOP_USER_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  
  flyway:
    url: ${MYSQL_BARBERSHOP_USER_URL}
    user: ${MYSQL_BARBERSHOP_USER_USERNAME}
    password: ${MYSQL_BARBERSHOP_USER_PASSWORD}
  
  jackson:
    default-property-inclusion: non-null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Sao_Paulo
    

